/**
 * APTET QUESTION POOL: Subject - IIA English Language Content (180 Questions)
 * Source PDF: English content 2A.pdf (Pages 2-35, Answer Key Pages 36-37)
 */
const ENGLISH_SUBJECT_180 = [
  {
    id: "ENG-SUB-001",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 2,
    sourceQuestionNumber: 1,
    topic: "Vocabulary",
    subtopic: "Synonyms",
    question: "Taro saw a beautiful little waterfall. Choose the synonym of the word 'beautiful'.",
    options: ["ugly", "unattractive", "displeasing", "good-looking"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-002",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 2,
    sourceQuestionNumber: 2,
    topic: "Vocabulary",
    subtopic: "Synonyms",
    question: "How much did you pay for that Hilsa? Choose the synonym of the word 'pay'.",
    options: ["refuse to give", "hold back", "keep hold of", "give payment"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-003",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 2,
    sourceQuestionNumber: 3,
    topic: "Vocabulary",
    subtopic: "Synonyms",
    question: "He breathed heavily. Choose the synonym of the word 'heavily'.",
    options: ["easily", "quickly", "with difficulty", "simply"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-004",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 2,
    sourceQuestionNumber: 4,
    topic: "Vocabulary",
    subtopic: "Antonyms",
    question: "Open your petals wide. Choose the antonym of the word 'wide'.",
    options: ["fully", "all the way", "completely", "partly"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-005",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 3,
    sourceQuestionNumber: 5,
    topic: "Vocabulary",
    subtopic: "Antonyms",
    question: "He grabbed a branch. Choose the antonym of the word 'grabbed'.",
    options: ["released", "seized", "grasped", "snatched"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-006",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 3,
    sourceQuestionNumber: 6,
    topic: "Vocabulary",
    subtopic: "Antonyms",
    question: "The horse galloped out of the stable. Choose the antonym of the word 'out'.",
    options: ["away", "not in", "in", "exposed"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-007",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 3,
    sourceQuestionNumber: 7,
    topic: "Vocabulary",
    subtopic: "Spelling",
    question: "Choose the correctly spelt word.",
    options: ["Pregncancy", "Pregnancy", "Pregnaency", "Pregniency"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-008",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 3,
    sourceQuestionNumber: 8,
    topic: "Vocabulary",
    subtopic: "Spelling",
    question: "Choose the correctly spelt word.",
    options: ["Senatoriail", "Senatoroyl", "Cenatorial", "Senatorial"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-009",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 3,
    sourceQuestionNumber: 9,
    topic: "Vocabulary",
    subtopic: "Spelling",
    question: "Choose the correctly spelt word.",
    options: ["Spandthtift", "Spendthrift", "Spendtrift", "Spendhtrift"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-010",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 3,
    sourceQuestionNumber: 10,
    topic: "Vocabulary",
    subtopic: "One-Word Substitutions",
    question: "A person who is not sure about the existence of God.",
    options: ["agnostic", "didactic", "verbose", "culprit"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-011",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 4,
    sourceQuestionNumber: 11,
    topic: "Vocabulary",
    subtopic: "One-Word Substitutions",
    question: "A person who is extremely important or large in size.",
    options: ["colossus", "culprit", "detractors", "publishers"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-012",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 4,
    sourceQuestionNumber: 12,
    topic: "Vocabulary",
    subtopic: "One-Word Substitutions",
    question: "A person who studies birds scientifically.",
    options: ["Ornithologist", "Archaeologist", "Psychologist", "Anthropologist"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-013",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 4,
    sourceQuestionNumber: 13,
    topic: "Vocabulary",
    subtopic: "Idioms",
    question: "Identify the meaning of the given idiom: 'head was in a whirl'.",
    options: ["Confused and unable to think clearly.", "Doing something", "Carefully corrected", "getting bored"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-014",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 4,
    sourceQuestionNumber: 14,
    topic: "Vocabulary",
    subtopic: "Idioms",
    question: "Our entire class is quacking in its boots. Identify the suitable meaning of the underlined part.",
    options: ["willing to do something", "be very worried", "suffering with pain", "joyful"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-015",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 4,
    sourceQuestionNumber: 15,
    topic: "Vocabulary",
    subtopic: "Idioms",
    question: "Identify the meaning of the Idiom 'fly high'.",
    options: ["Be polite", "Be humble", "Be successful", "Be perfect"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-016",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 4,
    sourceQuestionNumber: 16,
    topic: "Vocabulary",
    subtopic: "Phrasal Verbs",
    question: "Choose the meaning of the Phrasal verb 'break down'.",
    options: ["to continue efforts.", "to complete the given tasks.", "to stop working because of a fault.", "to have control."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-017",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 5,
    sourceQuestionNumber: 17,
    topic: "Vocabulary",
    subtopic: "Phrasal Verbs",
    question: "Choose the meaning of the Phrasal verb 'fed up'.",
    options: ["tired and happy", "surprised and shocked", "tired and unhappy", "smiled and cried"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-018",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 5,
    sourceQuestionNumber: 18,
    topic: "Vocabulary",
    subtopic: "Phrasal Verbs",
    question: "If you carry on spending money like this, you will end up in debt. Identify the meaning of 'carry on'.",
    options: ["stop", "behave", "continue", "improve"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-019",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 5,
    sourceQuestionNumber: 19,
    topic: "Vocabulary",
    subtopic: "Proverbs",
    question: "Akash always helps his family members first before helping others in the village. Choose the correct proverb for the situation.",
    options: ["Every cloud has a silver lining.", "Charity begins at home.", "Care is no cure.", "Carry your own cross."],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-020",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 5,
    sourceQuestionNumber: 20,
    topic: "Vocabulary",
    subtopic: "Proverbs",
    question: "Everyone laughed at Meena's simple dress, but she won the first prize in the science competition. Choose the correct proverb for the situation.",
    options: ["Practice makes perfect.", "Where there is a will, there is a way.", "Do not judge a book by its cover.", "Too many cooks spoil the broth."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-021",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 5,
    sourceQuestionNumber: 21,
    topic: "Vocabulary",
    subtopic: "Proverbs",
    question: "After playing for hours in the hot sun, the children enjoyed even the simple meal of rice and pickle as if it were a feast. Choose the correct proverb.",
    options: ["Health is wealth.", "Home is where the heart is.", "Honey in the mouth, bile in the heart.", "Hunger is the best sauce."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-022",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 6,
    sourceQuestionNumber: 22,
    topic: "Vocabulary",
    subtopic: "Homophones",
    question: "I have kept a ___ to write about my father's milk ___.",
    options: ["diary, dairy", "dairy, diary", "dairy, dairy", "diary, diary"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-023",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 6,
    sourceQuestionNumber: 23,
    topic: "Vocabulary",
    subtopic: "Homophones",
    question: "Giving up this piece of land will bring a lot of peace in this region. In the given sentence, the underlined words are called:",
    options: ["Homonyms", "Homographs", "Homophones", "Colocations"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-024",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 6,
    sourceQuestionNumber: 24,
    topic: "Vocabulary",
    subtopic: "Homonyms",
    question: "A word that is spelt like another word or pronounced like it but that has a different meaning is called:",
    options: ["Homophone", "Homonym", "Homograph", "Collocation"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-025",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 6,
    sourceQuestionNumber: 25,
    topic: "Vocabulary",
    subtopic: "Suffixes",
    question: "Which of the following suffix converts the given adjective 'new' into a noun?",
    options: ["-ly", "-ful", "-ness", "-able"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-026",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 6,
    sourceQuestionNumber: 26,
    topic: "Vocabulary",
    subtopic: "Prefixes",
    question: "By adding which of the following prefix to the word 'weight', we get the meaning thin or weak?",
    options: ["semi-", "over-", "anti-", "under-"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-027",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 7,
    sourceQuestionNumber: 27,
    topic: "Vocabulary",
    subtopic: "Suffixes",
    question: "Choose the word with a suffix that means 'without'.",
    options: ["reachable", "careless", "invincible", "kindness"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-028",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 7,
    sourceQuestionNumber: 28,
    topic: "Vocabulary",
    subtopic: "Collocations",
    question: "The university ___ the honorary degree on the social worker.",
    options: ["deferred", "conferred", "confirmed", "collocated"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-029",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 7,
    sourceQuestionNumber: 29,
    topic: "Vocabulary",
    subtopic: "Collocations",
    question: "He was arrested in ___ driving case.",
    options: ["danger", "faster", "speed", "drunken"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-030",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 7,
    sourceQuestionNumber: 30,
    topic: "Vocabulary",
    subtopic: "Collocations",
    question: "The ___ growth of real estate poses a serious threat to our environment.",
    options: ["increase", "gradual", "quickly", "rapid"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-031",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 7,
    sourceQuestionNumber: 31,
    topic: "Vocabulary",
    subtopic: "Foreign Phrases",
    question: "Identify the meaning of the given foreign phrase: 'viva voce'.",
    options: ["vice president", "very important", "a spoken exam", "volunteer"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-032",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 8,
    sourceQuestionNumber: 32,
    topic: "Vocabulary",
    subtopic: "Foreign Phrases",
    question: "Identify the meaning of the given foreign phrase: 'bon voyage'.",
    options: ["Congratulations", "Happy birthday", "Have a good journey", "Wish you good luck"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-033",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 8,
    sourceQuestionNumber: 33,
    topic: "Vocabulary",
    subtopic: "Foreign Phrases",
    question: "Choose the foreign phrase that means a link language.",
    options: ["en masse", "sine die", "lingua franca", "adhoc"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-034",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 8,
    sourceQuestionNumber: 34,
    topic: "Grammar",
    subtopic: "Tenses",
    question: "I ___ (work) at the computer since 5 a.m.",
    options: ["has been working", "am working", "have been working", "am been working"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-035",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 8,
    sourceQuestionNumber: 35,
    topic: "Grammar",
    subtopic: "Tenses",
    question: "The earth ___ (revolve) round the sun.",
    options: ["revolving", "revolved", "revolves", "revolve"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-036",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 8,
    sourceQuestionNumber: 36,
    topic: "Grammar",
    subtopic: "Tenses",
    question: "The cost of living ___ (increase) day by day.",
    options: ["was increased", "increase", "is increasing", "increasing"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-037",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 9,
    sourceQuestionNumber: 37,
    topic: "Grammar",
    subtopic: "Articles",
    question: "He is ___ honest man.",
    options: ["a", "an", "the", "no article"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-038",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 9,
    sourceQuestionNumber: 38,
    topic: "Grammar",
    subtopic: "Articles",
    question: "He can play ___ flute.",
    options: ["a", "an", "the", "no article"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-039",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 9,
    sourceQuestionNumber: 39,
    topic: "Grammar",
    subtopic: "Articles",
    question: "I usually have ___ lunch at 2pm.",
    options: ["a", "an", "the", "no article"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-040",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 9,
    sourceQuestionNumber: 40,
    topic: "Grammar",
    subtopic: "Prepositions",
    question: "The cat jumped ___ the chair.",
    options: ["of", "off", "to", "on"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-041",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 9,
    sourceQuestionNumber: 41,
    topic: "Grammar",
    subtopic: "Prepositions",
    question: "I've been waiting ___ 40minutes.",
    options: ["for", "since", "from", "to"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-042",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 10,
    sourceQuestionNumber: 42,
    topic: "Grammar",
    subtopic: "Prepositions",
    question: "I'll wait ___ you're ready.",
    options: ["after", "unless", "while", "until"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-043",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 10,
    sourceQuestionNumber: 43,
    topic: "Grammar",
    subtopic: "Clauses",
    question: "Choose the adjective clause in the given sentence: 'The dog that bites does not bark.'",
    options: ["The dog", "that bites", "does not", "bark"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-044",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 10,
    sourceQuestionNumber: 44,
    topic: "Grammar",
    subtopic: "Clauses",
    question: "Choose the suitable adverb clause that fits in the blank: 'Fools rush in ___.'",
    options: ["where I had left them", "because he is arrogant", "if we don't take a taxi", "where wise men fear to tread"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-045",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 10,
    sourceQuestionNumber: 45,
    topic: "Grammar",
    subtopic: "Clauses",
    question: "No one knows who he is. The underlined part in the above sentence is a:",
    options: ["Noun clause", "Adjective clause", "Adverb clause", "Main clause"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-046",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 10,
    sourceQuestionNumber: 46,
    topic: "Grammar",
    subtopic: "Degrees of Comparison",
    question: "Change into Comparative Degree: 'No other city in India is as big as Mumbai.'",
    options: ["Mumbai in India is very big.", "Mumbai is the biggest city in India.", "Mumbai is bigger than any other city in India.", "Mumbai is bigger of all cities in India."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-047",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 11,
    sourceQuestionNumber: 47,
    topic: "Grammar",
    subtopic: "Degrees of Comparison",
    question: "Fill in the blank with suitable degree of the adjective given: 'My new car is ___ than my old one (fast).'",
    options: ["fastest", "the fastest", "faster", "fast"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-048",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 11,
    sourceQuestionNumber: 48,
    topic: "Grammar",
    subtopic: "Degrees of Comparison",
    question: "Change the following sentence into positive degree: 'The pen is mightier than the sword.'",
    options: ["The sword is mightier than the pen.", "The sword is not so mighty as the pen.", "No other pen is as mighty as sword.", "The sword is so mighty as the pen."],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-049",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 11,
    sourceQuestionNumber: 49,
    topic: "Grammar",
    subtopic: "Language Functions",
    question: "Identify the sentence expressing 'possibility'.",
    options: ["May I leave the class?", "May God bless you!", "You may go.", "We may attend the birth day party."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-050",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 11,
    sourceQuestionNumber: 50,
    topic: "Grammar",
    subtopic: "Language Functions",
    question: "Choose the language function of the given sentence: 'Shall I Carry your luggage?'",
    options: ["Suggestion", "Permission", "Offer", "Request"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-051",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 11,
    sourceQuestionNumber: 51,
    topic: "Grammar",
    subtopic: "Language Functions",
    question: "Choose the language function of the given sentence: 'May God bless you!'",
    options: ["Possibility", "Permission", "Cursing", "Blessing"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-052",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 12,
    sourceQuestionNumber: 52,
    topic: "Grammar",
    subtopic: "Question Tags",
    question: "We have met before, ___",
    options: ["have we?", "haven't we?", "aren't we?", "are we?"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-053",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 12,
    sourceQuestionNumber: 53,
    topic: "Grammar",
    subtopic: "Question Tags",
    question: "He lives in France, ___",
    options: ["doesn't she?", "doesn't it?", "doesn't he?", "does he?"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-054",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 12,
    sourceQuestionNumber: 54,
    topic: "Grammar",
    subtopic: "Question Tags",
    question: "She can't drive, ___",
    options: ["is she?", "can she?", "are she?", "has she?"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-055",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 12,
    sourceQuestionNumber: 55,
    topic: "Grammar",
    subtopic: "Sentence Types",
    question: "Three butterflies lived in a garden. Identify the type of sentence.",
    options: ["Declarative", "Interrogative", "Imperative", "Exclamatory"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-056",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 12,
    sourceQuestionNumber: 56,
    topic: "Grammar",
    subtopic: "Sentence Types",
    question: "How cold the night is! Identify the type of sentence.",
    options: ["Declarative", "Exclamatory", "Interrogative", "Imperative"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-057",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 13,
    sourceQuestionNumber: 57,
    topic: "Grammar",
    subtopic: "Sentence Types",
    question: "Have mercy upon us. Identify the type of sentence.",
    options: ["Assertive", "Interrogative", "Imperative", "Exclamatory"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-058",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 13,
    sourceQuestionNumber: 58,
    topic: "Grammar",
    subtopic: "Direct and Indirect Speech",
    question: "\"I took it home with me,\" she said. Choose the correct Indirect speech.",
    options: ["She said that she took it home with me.", "She said that she took it home with her.", "She said that had taken it home with him.", "She said that she had taken it home with her."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-059",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 13,
    sourceQuestionNumber: 59,
    topic: "Grammar",
    subtopic: "Direct and Indirect Speech",
    question: "He said, \"I have lost my umbrella.\" Choose the correct Indirect speech.",
    options: ["He said that he had lost my umbrella.", "He said that he had lost his umbrella.", "He said that she had lost his umbrella.", "He said that she had lost her umbrella."],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-060",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 13,
    sourceQuestionNumber: 60,
    topic: "Grammar",
    subtopic: "Direct and Indirect Speech",
    question: "He said, \"Where is she going?\" Choose the correct Indirect speech.",
    options: ["He asked where is he going.", "He asked that where was she going.", "He asked where she was going.", "He asked where she is going."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-061",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 13,
    sourceQuestionNumber: 61,
    topic: "Grammar",
    subtopic: "Active and Passive Voice",
    question: "The little girl caught the ball. Choose the correct passive voice.",
    options: ["The ball is caught by the little girl.", "The ball has caught by the girl.", "The ball was caught by the little girl.", "The ball were caught by the little girl."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-062",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 13,
    sourceQuestionNumber: 62,
    topic: "Grammar",
    subtopic: "Active and Passive Voice",
    question: "They are repairing the bridge. Choose the correct passive voice.",
    options: ["The bridge was being repaired by them.", "The bridge has been repaired by them.", "The bridge had been repaired by them.", "The bridge is being repaired by them."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-063",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 14,
    sourceQuestionNumber: 63,
    topic: "Grammar",
    subtopic: "Active and Passive Voice",
    question: "She has packed the books. Choose the correct passive voice.",
    options: ["The books has been packed by her.", "The books had been packed by her.", "The books have been packed by her.", "The books are been packed by her."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-064",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 14,
    sourceQuestionNumber: 64,
    topic: "Grammar",
    subtopic: "Tenses",
    question: "He liked that place very much. Identify the tense of the following sentence.",
    options: ["Simple past tense", "Simple present tense", "Simple future tense", "Past perfect tense"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-065",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 14,
    sourceQuestionNumber: 65,
    topic: "Grammar",
    subtopic: "Tenses",
    question: "The ants were going in a line. Identify the tense of the following sentence.",
    options: ["Simple present tense", "Present continuous tense", "Simple past tense", "Past continuous tense"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-066",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 14,
    sourceQuestionNumber: 66,
    topic: "Grammar",
    subtopic: "Tenses",
    question: "The entire field had become wet. Identify the tense of the following sentence.",
    options: ["Present perfect tense", "Past perfect tense", "Present continuous tense", "Past continuous tense"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-067",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 14,
    sourceQuestionNumber: 67,
    topic: "Grammar",
    subtopic: "Subject-Verb Agreement",
    question: "Neither of the two men ___ very strong. Choose the correct option.",
    options: ["was", "were", "are", "have"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-068",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 15,
    sourceQuestionNumber: 68,
    topic: "Grammar",
    subtopic: "Subject-Verb Agreement",
    question: "The jury ___ divided in their opinions. Choose the correct option.",
    options: ["is", "was", "are", "has"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-069",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 15,
    sourceQuestionNumber: 69,
    topic: "Grammar",
    subtopic: "Subject-Verb Agreement",
    question: "Choose the sentence which has correct agreement of the verb with its subject.",
    options: ["He and I was playing.", "Either the cat or the dog have been here.", "The news is true.", "Neither you nor he are to blame."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-070",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 15,
    sourceQuestionNumber: 70,
    topic: "Grammar",
    subtopic: "Sentence Rearrangement",
    question: "Put the words in correct order to make a meaningful sentence: to work(A)/ every day(B)/ walks(C)/ Lisa(D)",
    options: ["CDAB", "ABDC", "BCDA", "DCAB"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-071",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 15,
    sourceQuestionNumber: 71,
    topic: "Grammar",
    subtopic: "Sentence Rearrangement",
    question: "Rearrange these words and make a meaningful sentence: she (A)/ everyday (B)/ a newspaper(C)/ reads(D)",
    options: ["CDBA", "ABDC", "ADCB", "DCAB"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-072",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 15,
    sourceQuestionNumber: 72,
    topic: "Grammar",
    subtopic: "Sentence Rearrangement",
    question: "Rearrange these words and make a meaningful sentence: immediately(A)/ called(B)/ she(C)/ back(D)/ me(E)",
    options: ["BCDEA", "CEBDA", "CBEDA", "CADEB"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-073",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 15,
    sourceQuestionNumber: 73,
    topic: "Grammar",
    subtopic: "Parts of Speech",
    question: "He owned a small hotel. Identify the part of speech of the word 'owned'.",
    options: ["Noun", "Verb", "Pronoun", "Adverb"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-074",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 16,
    sourceQuestionNumber: 74,
    topic: "Grammar",
    subtopic: "Parts of Speech",
    question: "A small baby is in a cradle. Identify the part of speech of the underlined word 'small'.",
    options: ["Noun", "Pronoun", "Adjective", "Adverb"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-075",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 16,
    sourceQuestionNumber: 75,
    topic: "Grammar",
    subtopic: "Parts of Speech",
    question: "The rabbit went to the cobbler. Identify the part of speech of the underlined word 'rabbit'.",
    options: ["Noun", "Pronoun", "Verb", "Adjective"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-076",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 16,
    sourceQuestionNumber: 76,
    topic: "Grammar",
    subtopic: "Conjunctions",
    question: "Catch me ___ you can. Choose the correct option.",
    options: ["so", "but", "or", "if"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-077",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 16,
    sourceQuestionNumber: 77,
    topic: "Grammar",
    subtopic: "Conjunctions",
    question: "Think of me ___ I'm away. Choose the correct option.",
    options: ["and", "or", "while", "so"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-078",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 16,
    sourceQuestionNumber: 78,
    topic: "Grammar",
    subtopic: "Conjunctions",
    question: "The match has been cancelled ___ the bad weather. Choose the correct option.",
    options: ["in spite of", "but", "because of", "in case"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-079",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 17,
    sourceQuestionNumber: 79,
    topic: "Grammar",
    subtopic: "Sentence Transformation",
    question: "Choose the correct compound sentence for the given simple sentence: 'With a great effort he lifted the box.'",
    options: ["He put forth a great effort and lifted the box.", "He lifted the box though it is heavy.", "The box is too heavy to lift for him.", "He lifted the heavy box."],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-080",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 17,
    sourceQuestionNumber: 80,
    topic: "Grammar",
    subtopic: "Sentence Transformation",
    question: "Identify the simple sentence among the following.",
    options: ["He said that he was innocent", "He confessed his fault.", "He worked hard yet did not succeed", "Be good and you will be happy"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-081",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 17,
    sourceQuestionNumber: 81,
    topic: "Grammar",
    subtopic: "Sentence Transformation",
    question: "Identify the complex sentence among the following.",
    options: ["We believe in his innocence.", "He declared his innocence.", "He is innocent and we believe it.", "He confessed that he was guilty."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-082",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 17,
    sourceQuestionNumber: 82,
    topic: "Grammar",
    subtopic: "Correct Sentence Usage",
    question: "Choose the correct sentence from the given.",
    options: ["I has a large family back in Patna.", "I have the big family back in Patna.", "I have a large family back in Patna.", "I has a big family back in Patna."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-083",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 17,
    sourceQuestionNumber: 83,
    topic: "Grammar",
    subtopic: "Error Detection",
    question: "Identify the part that has an error in the given sentence: No sooner did she pour the cake batter(a)/in the baking dish(b)/ then the light started to fluctuate(c)/ No error(d)",
    options: ["d", "a", "b", "c"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-084",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 17,
    sourceQuestionNumber: 84,
    topic: "Grammar",
    subtopic: "Correct Sentence Usage",
    question: "Identify the correct sentence from the given.",
    options: ["My brother lives abroad.", "My brother lives in abroad.", "My brother lives at abroad.", "My brother living in abroad."],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-085",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 18,
    sourceQuestionNumber: 85,
    topic: "Reading",
    subtopic: "Comprehension",
    question: "Long ago Queen Ahilya Bai ruled over Maheswar, a place in Madhya Pradesh. She was a warrior queen who ordered to build a strong and beautiful fort on the banks of the Narmada River. This queen had the fortress built on a hill, and from there, she could see her entire kingdom of Maheswar. This fort is also known as Ahilya Fort.\nWhere is Maheswar Fort located?",
    options: ["On the banks of the Narmada River", "In Andhra Pradesh", "At the foot of a hill", "On the bank of a canal"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-086",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 18,
    sourceQuestionNumber: 86,
    topic: "Reading",
    subtopic: "Comprehension",
    question: "Once upon a time in a small village at the foot of the mighty Himalayas, lived a young girl named Minam. She loved to listen to stories about the mountains from her grandfather, who was once a Sherpa.\nWhat was Minam's grandfather?",
    options: ["A farmer", "A mountaineer", "A Sherpa", "A musician"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-087",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 18,
    sourceQuestionNumber: 87,
    topic: "Reading",
    subtopic: "Comprehension",
    question: "Once upon a time, in the state of Nagaland, humans and animals lived together. They had a disagreement about their superiority. The humans challenged the tiger and the challenge came to be known as 'Hekko', The word 'Hekko' meant 'Challenging the tiger'.\nWhat is meant by \"Hekko\"?",
    options: ["Challenging the animals", "Challenging the humans", "Challenging the tiger", "Challenging the challenge"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-088",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 19,
    sourceQuestionNumber: 88,
    topic: "Reading",
    subtopic: "Comprehension",
    question: "There was a girl named Rani who lived in a village. She was very curious and used to ask many questions to her family, teachers and friends. \"Why is the sky blue?\", \"Where does the sun go at night?\"\nChoose the incorrect option based on the above paragraph.",
    options: ["Rani lived in a village.", "Rani was very curious.", "Rani used to ask why the sky was blue.", "Rani never asked any questions."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-089",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 19,
    sourceQuestionNumber: 89,
    topic: "Reading",
    subtopic: "Comprehension",
    question: "Madhu loved food. He always wanted to eat different kinds of food and snacks. He was never tired of eating. Every day, at noon, he would sit under a banyan tree and eat his lunch. One day, as he was eating, an old man came.\nChoose the correct statement based on the passage.",
    options: ["Madhu loved sleeping.", "He was never tired of playing.", "He would sit on the branches of a Mango tree.", "Madhu enjoyed eating."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-090",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 19,
    sourceQuestionNumber: 90,
    topic: "Reading",
    subtopic: "Comprehension",
    question: "Once upon a time, there was a farmer who liked fruits. So, he decided to grow fruits on his land. He worked hard to grow a variety of fruits. With hard work and care, the trees grew well. When the fruits were all ripe and ready to be eaten, the farmer decided to gift the best fruit to the king.\nChoose the incorrect statement based on the passage.",
    options: ["The farmer liked fruits.", "He decided to gift the stale fruits to the king.", "He worked hard to grow the fruits.", "He decided to grow fruits on his land."],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-091",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 20,
    sourceQuestionNumber: 91,
    topic: "Literature",
    subtopic: "Literary Forms",
    question: "Which dramatic genre typically features a serious story that ends in sorrow or the down fall of the main character?",
    options: ["Comedy", "Melodrama", "Farce", "Tragedy"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-092",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 20,
    sourceQuestionNumber: 92,
    topic: "Literature",
    subtopic: "Literary Forms",
    question: "How many lines does a traditional sonnet contain?",
    options: ["14 lines", "12 lines", "13 lines", "11 lines"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-093",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 20,
    sourceQuestionNumber: 93,
    topic: "Literature",
    subtopic: "Literary Forms",
    question: "The primary thematic focus of a traditional elegy is a/an:",
    options: ["folklore", "nature's song", "epic", "reflective poem expressing sorrow"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-094",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 20,
    sourceQuestionNumber: 94,
    topic: "Literature",
    subtopic: "Prose",
    question: "The best example for a short story is:",
    options: ["Paradise lost", "Ode to Nightingale", "The Necklace", "Twelfth night"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-095",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 20,
    sourceQuestionNumber: 95,
    topic: "Literature",
    subtopic: "Prose",
    question: "\"Studies serve for delight, for ornament, and for ability\" are the famous lines extracted from the essay:",
    options: ["Population", "Of Studies", "Prefaces", "Macaulay's essays"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-096",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 20,
    sourceQuestionNumber: 96,
    topic: "Literature",
    subtopic: "Novel",
    question: "\"A long narrative in prose, detailing the actions of fictious people\" is called:",
    options: ["The short story", "The masque", "The Novel", "Drama"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-097",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 21,
    sourceQuestionNumber: 97,
    topic: "Literature",
    subtopic: "Drama",
    question: "A speech at the beginning of a play, book or film that introduces is called a/an:",
    options: ["epilogue", "monologue", "prologue", "imagery"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-098",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 21,
    sourceQuestionNumber: 98,
    topic: "Literature",
    subtopic: "Drama",
    question: "Which of the following Shakespearean work is the example of Romantic comedy?",
    options: ["Hamlet", "Twelfth Night", "The Merchant of Venice", "Romeo and Juliet"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-099",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 21,
    sourceQuestionNumber: 99,
    topic: "Literature",
    subtopic: "Drama",
    question: "A speech in a play in which a character, who is alone on the stage, speaks his or her thoughts is called:",
    options: ["monologue", "narration", "epilogue", "soliloquy"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-100",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 21,
    sourceQuestionNumber: 100,
    topic: "Literature",
    subtopic: "Literary Concepts",
    question: "An implied Simile is called:",
    options: ["Personification", "Metaphor", "Metonomy", "Irony"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-101",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 21,
    sourceQuestionNumber: 101,
    topic: "Literature",
    subtopic: "Literary Concepts",
    question: "A direct address to the dead, to the absent or to a personified object is called:",
    options: ["Personification", "Metaphor", "Irony", "Apostrophe"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-102",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 21,
    sourceQuestionNumber: 102,
    topic: "Literature",
    subtopic: "Literary Concepts",
    question: "\"The pen is mightier than the sword\" is an example of:",
    options: ["Metonomy", "Irony", "Synecdoche", "Alliteration"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-103",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 22,
    sourceQuestionNumber: 103,
    topic: "Literature",
    subtopic: "Poetry",
    question: "According to Tagore in the poem \"Where the Mind is Without Fear\" why do we stretch our arms?",
    options: ["To embrace our religion", "To get perfection", "To wrap our arms around loved ones", "To get wealth"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-104",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 22,
    sourceQuestionNumber: 104,
    topic: "Literature",
    subtopic: "Poetry",
    question: "Rabindranath Tagore's poem \"Where the Mind is Without Fear\" is extracted from:",
    options: ["Endymion", "Novum Organum", "Lyrical Ballads", "Gitanjali"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-105",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 22,
    sourceQuestionNumber: 105,
    topic: "Literature",
    subtopic: "Poetry",
    question: "According to Tagore in the poem \"Where the Mind is Without Fear\" our thought and action should be:",
    options: ["ever widening", "narrow", "broken", "cripple"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-106",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 22,
    sourceQuestionNumber: 106,
    topic: "Literature",
    subtopic: "Poetry",
    question: "What does the word 'Slumber' mean in the Wordsworth's poem \"A slumber Did My Spirit Seal\"?",
    options: ["Shepherd", "Doctor", "Dawn", "Deep sleep"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-107",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 22,
    sourceQuestionNumber: 107,
    topic: "Literature",
    subtopic: "Poetry",
    question: "What is the theme of William Wordsworth's poem \"A Slumber Did My Spirit Seal\"?",
    options: ["Admiring the nature", "The death of a loved one", "Celebrating his birth", "Wedding ceremony"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-108",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 23,
    sourceQuestionNumber: 108,
    topic: "Literature",
    subtopic: "Poetry",
    question: "In Wordsworth poem \"A Slumber Did My Spirit Seal\", Why can't she see or hear anything?",
    options: ["Because she was paralyzed.", "Because she was bed ridden.", "Because she was dead.", "Because she had met with an accident."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-109",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 23,
    sourceQuestionNumber: 109,
    topic: "Literature",
    subtopic: "Prose",
    question: "According to Sir Francis Bacon bowling is good for:",
    options: ["lungs", "digestion", "head", "kidneys"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-110",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 23,
    sourceQuestionNumber: 110,
    topic: "Literature",
    subtopic: "Authors & Works",
    question: "Who is regarded as the \"Father of English Essay\"?",
    options: ["Charles Dickens", "Francis Bacon", "William Shakespeare", "George Orwell"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-111",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 23,
    sourceQuestionNumber: 111,
    topic: "Literature",
    subtopic: "Prose",
    question: "According to Sir Francis Bacon, Crafty men contemn studies, Simple men admire them, And wise men:",
    options: ["teach", "apply", "preach", "think"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-112",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 23,
    sourceQuestionNumber: 112,
    topic: "Literature",
    subtopic: "Prose",
    question: "According to Rajaji, universities are the hopes of our: (What Makes a Nation)",
    options: ["national leaders", "common people", "scientists", "entrepreneurs"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-113",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 24,
    sourceQuestionNumber: 113,
    topic: "Literature",
    subtopic: "Authors & Works",
    question: "Who was popularly known as C.R?",
    options: ["Gandhiji", "Rajaji", "Nehruji", "Nanaji"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-114",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 24,
    sourceQuestionNumber: 114,
    topic: "Literature",
    subtopic: "Prose",
    question: "Rajaji delivered an inspirational speech \"What Makes a Nation\" at:",
    options: ["Indian Institute of Technology, Gowhathi.", "Indian Institute of Management, Ahmedabad.", "National Institute of Technology, Warangal.", "Lakshminarayan Institute of Technology, Nagpur."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-115",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 24,
    sourceQuestionNumber: 115,
    topic: "Literature",
    subtopic: "Novel",
    question: "Where was old major's dead body buried?",
    options: ["at the foot of a mountain", "on the bank of the river", "at the foot of the orchard", "at the corner of Jones bedroom"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-116",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 24,
    sourceQuestionNumber: 116,
    topic: "Literature",
    subtopic: "Novel",
    question: "Who is the owner of Manor Farm?",
    options: ["Old Major", "Snowball", "Mr. Jones", "Mrs. Jones"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-117",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 24,
    sourceQuestionNumber: 117,
    topic: "Literature",
    subtopic: "Novel",
    question: "Where were the seven commandments written?",
    options: ["on the five- barred gate", "on a small straw hat", "inside the big barn wall", "on the tarred wall"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-118",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 24,
    sourceQuestionNumber: 118,
    topic: "Literature",
    subtopic: "Novel",
    question: "Which of the following is not included in the seven commandments in \"Animal Farm\"?",
    options: ["No animal shall drink alcohol", "No animal shall wear clothes", "All animals are not equal", "No animal shall sleep in a bed."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-119",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 25,
    sourceQuestionNumber: 119,
    topic: "Literature",
    subtopic: "Novel",
    question: "Whose favourite maxims are \"I will work harder; Comrade Napoleon is always right\":",
    options: ["Old major", "Squealer", "Mollie", "Boxer"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-120",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 25,
    sourceQuestionNumber: 120,
    topic: "Literature",
    subtopic: "Novel",
    question: "What is the title of the Animal song?",
    options: ["Beasts of Ireland", "Beasts of England", "Beasts of Scotland", "Beasts of Animal Farm"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-121",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 25,
    sourceQuestionNumber: 121,
    topic: "Literature",
    subtopic: "Novel",
    question: "What the narrative point of view does Harper Lee use to tell 'To kill a Mockingbird'?",
    options: ["Third-Person omniscient", "First- person", "Second- person", "Third-person limited"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-122",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 25,
    sourceQuestionNumber: 122,
    topic: "Literature",
    subtopic: "Novel",
    question: "Who is the narrator of the novel 'To kill a Mockingbird'?",
    options: ["Boo Radley", "Scout Finch", "Atticus Finch", "Jem Finch"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-123",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 25,
    sourceQuestionNumber: 123,
    topic: "Literature",
    subtopic: "Novel",
    question: "During the main events of the book, 'To kill a Mockingbird' how does Scout experience the world around her?",
    options: ["As a young and growing girl", "As a teacher", "As an adult judge", "As a reporter from another town"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-124",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 26,
    sourceQuestionNumber: 124,
    topic: "Literature",
    subtopic: "Novel",
    question: "Who saves Jem and Scout from being attacked on Halloween night?",
    options: ["Atticus Finch", "Boo Radley", "Bob Ewell", "Tom Robinson"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-125",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 26,
    sourceQuestionNumber: 125,
    topic: "Literature",
    subtopic: "Novel",
    question: "What is the real name of the reclusive neighbour, Boo Radley?",
    options: ["Arthur Radley", "Nathan Radley", "Tom Radley", "James Radley"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-126",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 26,
    sourceQuestionNumber: 126,
    topic: "Literature",
    subtopic: "Novel",
    question: "What is the profession of Atticus Finch?",
    options: ["Lawyer", "Teacher", "Doctor", "Farmer"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-127",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 26,
    sourceQuestionNumber: 127,
    topic: "Literature",
    subtopic: "Drama",
    question: "Identify the subtitle of the Shakespearean drama 'Twelfth Night'.",
    options: ["As you will", "What you desire", "What you wish", "What you will"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-128",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 26,
    sourceQuestionNumber: 128,
    topic: "Literature",
    subtopic: "Drama",
    question: "What are the twin characters in the Shakespearean drama 'Twelfth Night'?",
    options: ["ORSINO and SEBASTIAN", "OLIVA and VIOLA", "SEBASTIAN and VIOLA", "FABIAN AND VIOLA"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-129",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 26,
    sourceQuestionNumber: 129,
    topic: "Literature",
    subtopic: "Drama",
    question: "Who was ORSINO in the drama 'Twelfth Night'?",
    options: ["Duke of Illyria", "Duke of Venice", "Duke of Britaine", "Duke of Austria"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-130",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 27,
    sourceQuestionNumber: 130,
    topic: "Literature",
    subtopic: "Drama",
    question: "In the Shakespearean play \"Twelfth night\" Act 1, Scene 1 begins at:",
    options: ["The sea- coast", "The Duke's place", "Olivia's house", "A street"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-131",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 27,
    sourceQuestionNumber: 131,
    topic: "Literature",
    subtopic: "Drama",
    question: "\"Some are born great, some achieve greatness and some have greatness thrust upon them\". The above famous lines are taken from:",
    options: ["Hamlet", "The Tempest", "Twelfth Night", "Othello"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-132",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 27,
    sourceQuestionNumber: 132,
    topic: "Literature",
    subtopic: "Drama",
    question: "The opening lines of the Shakespearean play \"Twelfth night\" are:",
    options: ["What country, friends, is this?", "I have sent after him.", "The climate's delicate, the air most sweet.", "If music be the food of love, play on."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-133",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 27,
    sourceQuestionNumber: 133,
    topic: "Literature",
    subtopic: "Drama",
    question: "Who plays dual role in the play \"The Importance of Being Earnest\"?",
    options: ["Algernon", "Fairfax", "Merriman", "Jack"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-134",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 27,
    sourceQuestionNumber: 134,
    topic: "Literature",
    subtopic: "Drama",
    question: "Who is Merriman in the play \"The Importance of Being Earnest\"?",
    options: ["Manservant", "Governess", "Butler", "Housemaid"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-135",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 28,
    sourceQuestionNumber: 135,
    topic: "Literature",
    subtopic: "Drama",
    question: "Who plays Piano in the beginning of the play \"The Importance of Being Earnest\"?",
    options: ["ALGERNON", "LANE", "JACK", "LADY BRACKNELL"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-136",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 28,
    sourceQuestionNumber: 136,
    topic: "Literature",
    subtopic: "Drama",
    question: "Where do Algernon Moncrieff live? (The Importance of Being Earnest)",
    options: ["In Manor House", "In Half-Moon street", "In Thames Street", "In Grosvenor street"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-137",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 28,
    sourceQuestionNumber: 137,
    topic: "Literature",
    subtopic: "Drama",
    question: "When Jack is forced to confess that he has no brother, what does he describe as a 'painful position' that he is 'inexperienced' in doing? (The importance of being Earnest)",
    options: ["Facing the anger of two young women", "Managing his family estate", "Breaking off an engagement", "Speaking the absolute truth"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-138",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 28,
    sourceQuestionNumber: 138,
    topic: "Literature",
    subtopic: "Drama",
    question: "In the play \"The Importance of Being Earnest' which is the only thing that consoles ALGERNON when he was in trouble?",
    options: ["Eating", "Drinking", "Chatting", "Meditating"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-139",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 28,
    sourceQuestionNumber: 139,
    topic: "Literature",
    subtopic: "Prose",
    question: "Where does the banker keep the lawyer imprisoned during the fifteen-year bet? (The Bet)",
    options: ["A public state prison downtown", "A small lodge in the banker's garden", "A secret underground dungeon", "A remote cabin"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-140",
    section: "englishLanguage2",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 29,
    sourceQuestionNumber: 140,
    topic: "Literature",
    subtopic: "Prose",
    question: "How much money does the banker bet the lawyer that he cannot stay in confinement for the agreed time? (The Bet)",
    options: ["Two million rubles", "One hundred thousand rubles", "Ten million rubles", "Five hundred thousand rubles"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-141",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 29,
    sourceQuestionNumber: 141,
    topic: "Literature",
    subtopic: "Prose",
    question: "How many years does the lawyer agree to spend in solitary confinement to win the bet? (The Bet)",
    options: ["5 years", "10 years", "15 years", "20 years"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-142",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 29,
    sourceQuestionNumber: 142,
    topic: "Literature",
    subtopic: "Prose",
    question: "In R.K Narayan's \"Engine Trouble\", what did the narrator win at the Gaiety show?",
    options: ["A pincushion", "A sewing machine", "A camera", "A road engine"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-143",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 29,
    sourceQuestionNumber: 143,
    topic: "Literature",
    subtopic: "Authors & Works",
    question: "What is the name of the imaginary town created by R.K Narayan? (Engine Trouble)",
    options: ["Phalgudi", "Thalgudi", "Malgudi", "Kalgudi"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-144",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 29,
    sourceQuestionNumber: 144,
    topic: "Literature",
    subtopic: "Prose",
    question: "Who performed the yogic feats in the story \"Engine Trouble\" by R.K Narayan?",
    options: ["Swamiji", "The Narrator", "The Municipal Chairman", "The Showman"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-145",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 30,
    sourceQuestionNumber: 145,
    topic: "ELT",
    subtopic: "Language Policy",
    question: "Which Governor General approved Macaulay's minutes on education in 1835?",
    options: ["William James", "Lord Dalhousie", "William Bentick", "William Mountbaten"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-146",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 30,
    sourceQuestionNumber: 146,
    topic: "ELT",
    subtopic: "Linguistics",
    question: "A polyglot is a person who is:",
    options: ["able to speak only one language", "able to speak mother tongue fluently.", "able to speak more than two languages", "able to speak English only."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-147",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 30,
    sourceQuestionNumber: 147,
    topic: "ELT",
    subtopic: "Commissions",
    question: "Which committee is also known as \"The University Education Commission\"?",
    options: ["Kothari Commission", "NPE- 1968", "Secondary Education Commission", "Dr. Sarvepally Radhakrishnan Committee"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-148",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 30,
    sourceQuestionNumber: 148,
    topic: "ELT",
    subtopic: "Methodology",
    question: "Which of the following is not the objective of teaching English?",
    options: ["To make learning an enjoyable activity.", "To help learners read and understand simple words, sentences and passages.", "To familiarize pupils with the spoken and written forms of English.", "To punish the learners for improving fluency."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-149",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 30,
    sourceQuestionNumber: 149,
    topic: "ELT",
    subtopic: "Assessment",
    question: "CCE is the paradigm shift in the teaching-learning process. CCE means…",
    options: ["Comprehensive Curriculum Efforts", "Continuous Comprehensive Evaluation", "Collective and Continuous Evaluation", "Competitive Comprehensive Evaluation"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-150",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 31,
    sourceQuestionNumber: 150,
    topic: "ELT",
    subtopic: "Language Skills",
    question: "Which statement supports English language fluency enhancement at school level?",
    options: ["Writing homework regularly.", "Establishing English Language Laboratory.", "Using Only Charts.", "Punishments given for wrongly spelt."],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-151",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 31,
    sourceQuestionNumber: 151,
    topic: "ELT",
    subtopic: "Policy Bodies",
    question: "The full form of CABE:",
    options: ["Common Academic Board of Education", "Central Academic Board of Education", "Central Advisory Board of Education", "Common Advisory Board on Education"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-152",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 31,
    sourceQuestionNumber: 152,
    topic: "ELT",
    subtopic: "History of Education",
    question: "The \"Magnacarta of Indian Education\" is:",
    options: ["Kothari commission", "Wood’s Despatch", "Yeshpal Committee", "NEP- 2020"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-153",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 31,
    sourceQuestionNumber: 153,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "English language has _____ distinct sounds or phonemes.",
    options: ["26", "44", "24", "48"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-154",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 31,
    sourceQuestionNumber: 154,
    topic: "ELT",
    subtopic: "Approaches & Methods",
    question: "S-O-S approach means:",
    options: ["Situational- Objective-structural approach.", "Structural- Oral- Situational approach.", "Situational- Oral- structural approach.", "Structural- Objective- situational approach."],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-155",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 31,
    sourceQuestionNumber: 155,
    topic: "ELT",
    subtopic: "Approaches & Methods",
    question: "Which is not the feature of Audio-Lingual Method?",
    options: ["Repetition drill", "Dialogue memorization", "Transformation drill", "Imagination"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-156",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 32,
    sourceQuestionNumber: 156,
    topic: "ELT",
    subtopic: "Approaches & Methods",
    question: "Who proposed Bilingual method?",
    options: ["Robert Lado", "Stephen Krashen", "lev Vygotsky", "Dr. C.J. Dodson"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-157",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 32,
    sourceQuestionNumber: 157,
    topic: "ELT",
    subtopic: "Pedagogy",
    question: "Which is not the feature of child-centered teaching?",
    options: ["Focuses on both meaning and form", "Directs to solve the tasks and understand the language better.", "Corporal punishments for wrong answers.", "Develops curiosity , creativity and critical thinking."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-158",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 32,
    sourceQuestionNumber: 158,
    topic: "ELT",
    subtopic: "Learning Concepts",
    question: "The existing knowledge of the learner is called ____",
    options: ["information", "ego", "schema", "technology"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-159",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 32,
    sourceQuestionNumber: 159,
    topic: "ELT",
    subtopic: "Second Language Acquisition",
    question: "Who introduced “The Input Hypothesis theory of Second language acquisition”?",
    options: ["Charles Darwin", "Ivan Pavlov", "Stephen Krashen", "Abraham Maslow"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-160",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 32,
    sourceQuestionNumber: 160,
    topic: "ELT",
    subtopic: "Teaching Techniques",
    question: "Substitution table can be used to teach:",
    options: ["articles", "structures", "determiners", "sounds"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-161",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 32,
    sourceQuestionNumber: 161,
    topic: "ELT",
    subtopic: "Linguistics",
    question: "The words which carry the meaning are called:",
    options: ["Content words", "Passive words", "Active voice", "Structural Words"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-162",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 33,
    sourceQuestionNumber: 162,
    topic: "ELT",
    subtopic: "Error Analysis",
    question: "Teachers correcting student’s errors at a later time without mentioning any names is called:",
    options: ["Error tolerance", "Error intolerance", "Error finding", "Fault finding"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-163",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 33,
    sourceQuestionNumber: 163,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "Vowel glides are also known as:",
    options: ["consonants", "punctuation", "monophthongs", "diphthongs"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-164",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 33,
    sourceQuestionNumber: 164,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "The sounds /p/ and /b/ are:",
    options: ["Plosives", "Nasals", "Affricates", "Laterals"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-165",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 33,
    sourceQuestionNumber: 165,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "Identify the phonetic script to the given word: 'Cease'",
    options: ["/ci:s/", "/tʃsi:s/", "/si:s/", "/ki:s/"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-166",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 33,
    sourceQuestionNumber: 166,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "‘Syllabification’ means:",
    options: ["join the vowels", "break the word into syllables", "identify the vowels", "counting the syllables"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-167",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 33,
    sourceQuestionNumber: 167,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "Identify the correct stress in the given word: 'engineer'",
    options: ["en'gineer", "engine'er", "engi'neer", "'engineer"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-168",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 34,
    sourceQuestionNumber: 168,
    topic: "ELT",
    subtopic: "Phonetics",
    question: "We use falling intonation in:",
    options: ["Requests", "Apologies", "Greetings", "Ordinary satements"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-169",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 34,
    sourceQuestionNumber: 169,
    topic: "ELT",
    subtopic: "Teaching Aids",
    question: "The expanded form of OHP is:",
    options: ["Overhead Pressure", "Overhead Projector", "Overhead Protection", "Overhead Project"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-170",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 34,
    sourceQuestionNumber: 170,
    topic: "ELT",
    subtopic: "Teaching Aids",
    question: "Choose the authentic material from the following.",
    options: ["Textbook", "Supplementary Reader", "Railway ticket", "Work book"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-171",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 34,
    sourceQuestionNumber: 171,
    topic: "ELT",
    subtopic: "Teaching Aids",
    question: "Teaching learning materials are used:",
    options: ["to make the classroom passive and inactive.", "to increase the boredom and fatigue.", "to suppress the innate abilities of the learners.", "to motivate the learners and make them understand the concepts easily."],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-172",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 34,
    sourceQuestionNumber: 172,
    topic: "ELT",
    subtopic: "Lesson Planning",
    question: "Steps involved in planning a poetry lesson:",
    options: ["Presentation, Appreciation, Preparation, Interpretation", "Preparation, Presentation, Interpretation, Appreciation", "Appreciation, Presentation, Interpretation, Preparation", "Interpretation, Preparation, Appreciation, Presentation"],
    correctOptionIndex: 1,
    correctOptionLetter: "B"
  },
  {
    id: "ENG-SUB-173",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 34,
    sourceQuestionNumber: 173,
    topic: "ELT",
    subtopic: "Linguistics",
    question: "In linguistics, the word ‘competence’ refers to a person’s:",
    options: ["knowledge of swimming", "knowledge of playing", "Subconscious Knowledge of rules governing the formation of speech", "Subconscious memory of beliefs and habits"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-174",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 174,
    topic: "ELT",
    subtopic: "Lesson Planning",
    question: "Lesson planning begins with:",
    options: ["selection of teaching aids", "strategies for developing skills", "writing objectives of the lesson", "evaluation"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-175",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 175,
    topic: "ELT",
    subtopic: "Curriculum",
    question: "The term ‘curriculum’ has been derived from the Latin word ‘Currere’. It means:",
    options: ["Designing", "Jumping", "Race course", "Play Ground."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-176",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 176,
    topic: "ELT",
    subtopic: "Acts & Policies",
    question: "RTE Act came into effect on:",
    options: ["1st January 2010", "1st August 2010", "1st April 2010", "1st September 2010"],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-177",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 177,
    topic: "ELT",
    subtopic: "Frameworks",
    question: "Identify the guiding principle that was not there in NCF-2005:",
    options: ["Child centered curriculum", "Learning should be interesting and joyful", "Encourage rote learning and by heart methods.", "Learning takes place both within and outside school."],
    correctOptionIndex: 2,
    correctOptionLetter: "C"
  },
  {
    id: "ENG-SUB-178",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 178,
    topic: "ELT",
    subtopic: "Testing & Evaluation",
    question: "Which is not the quality of a good test?",
    options: ["Ambiguity", "Validity", "Reliability", "Usability"],
    correctOptionIndex: 0,
    correctOptionLetter: "A"
  },
  {
    id: "ENG-SUB-179",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 179,
    topic: "ELT",
    subtopic: "Testing & Evaluation",
    question: "Assessment of learning is:",
    options: ["Self Assessment", "Formative Assessment", "Peer Assessment", "Summative Assessment"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  },
  {
    id: "ENG-SUB-180",
    section: "englishSubject",
    sourcePDF: "English content 2A.pdf",
    sourcePage: 35,
    sourceQuestionNumber: 180,
    topic: "ELT",
    subtopic: "Taxonomy",
    question: "Which domain is not in the Bloom’s Taxonomy?",
    options: ["Cognitive", "Affective", "Psychomotor", "Physiological"],
    correctOptionIndex: 3,
    correctOptionLetter: "D"
  }
];

// Single clean export variable consumed by index.html / script.js
const ENGLISH_SUBJECT_POOL = ENGLISH_SUBJECT_180;